# Generated by Django 4.1.4 on 2022-12-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="location_id",
            new_name="location",
        ),
    ]
